# Copyright 2023 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

# golangci-lint v2 configuration
version: "2"

linters:
  enable:
    - errcheck
    - gosec
    - gocritic
    - misspell
    - revive
    - unused

formatters:
  enable:
    - gofmt
    - goimports

issues:
  uniq-by-line: false

run:
  issues-exit-code: 1
  timeout: 10m